services:
  pdsim-server:
    build: .
    image: pdsim-server:latest
    volumes:
      - ./data:/data
    ports:
      - "5556:5556"
    network_mode: host
    stdin_open: true 
    tty: true        
